name: CI/CD - Build, Test, Deploy to App Service, Upload Log to Azure

on:
  push:
    branches: [ 'master', 'main' ]
  pull_request:
    branches: [ 'master', 'main' ]
  workflow_dispatch:

# Required repo secrets (set these in repo Settings → Secrets):
# - AZURE_CREDENTIALS           : service principal SDK auth JSON (for azure/login)
# - AZURE_STORAGE_CONNECTION_STRING : storage account connection string (used to upload logs)
# - AZURE_STORAGE_CONTAINER     : container name to store logs (e.g. 'poc')
# - AZURE_WEBAPP_NAME           : App Service name to deploy to
# - AZURE_RESOURCE_GROUP        : Resource group where the App Service lives or will be created
# Optional secrets:
# - AZURE_WEBAPP_PLAN          : App Service plan name (will be created if missing)
# - AZURE_LOCATION             : Azure location (default: eastus)

env:
  AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  AZURE_WEBAPP_PLAN: ${{ secrets.AZURE_WEBAPP_PLAN }}
  AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test (capture log)
        run: |
          mvn -B clean verify | tee build-devops.log

      - name: Upload build log as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: build-devops-log
          path: build-devops.log

      - name: Try Azure OIDC login (recommended)
        id: azure_oidc_login
        uses: azure/login@v1
        continue-on-error: true
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Detect Azure login failure and append to log
        if: ${{ always() }}
        run: |
          # If az account show fails, write a clear message to build-devops.log so it's uploaded
          if ! az account show >/dev/null 2>&1; then
            echo "--- AZURE LOGIN FAILED ---" >> build-devops.log || true
            echo "Azure login failed. This is commonly caused by Conditional Access policies blocking service principal credential flows (AADSTS53003) or misconfigured credentials." >> build-devops.log || true
            echo "Error details: (check Actions run logs for step 'Try Azure OIDC login' for the provider error message)" >> build-devops.log || true
            echo "If your tenant blocks non-interactive credential flows, configure federated credentials (OIDC) for your GitHub Actions app registration. See: https://github.com/azure/login#configure-a-service-principal-with-a-federated-credential-to-use-oidc-based-authentication" >> build-devops.log || true
            echo "Workflow run URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> build-devops.log || true
          else
            echo "Azure login succeeded." >> build-devops.log || true
          fi

      - name: Ensure Azure CLI and jq installed (for manual login fallback)
        run: |
          set -e
          echo "Ensuring azure-cli and jq are available"
          sudo apt-get update && sudo apt-get install -y ca-certificates curl apt-transport-https lsb-release gnupg jq
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/ || true
          CODENAME="$(lsb_release -cs)"
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $CODENAME main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update && sudo apt-get install -y azure-cli || true

      - name: Fallback: Manual Azure login and capture errors to log
        continue-on-error: true
        run: |
          set -e
          echo "Checking if Azure login is already present..."
          if az account show >/dev/null 2>&1; then
            echo "Azure already logged in; skipping manual login." >> build-devops.log || true
            exit 0
          fi
          echo "Attempting manual az login using service principal from AZURE_CREDENTIALS (output appended to build-devops.log)"
          AZURE_CREDENTIALS='${{ secrets.AZURE_CREDENTIALS }}'
          if [ -z "$AZURE_CREDENTIALS" ]; then
            echo "No AZURE_CREDENTIALS secret found; skipping manual login." >> build-devops.log || true
            exit 0
          fi
          # write creds to temp file (kept on runner only) and extract fields safely
          printf '%s' "$AZURE_CREDENTIALS" > /tmp/azure_creds.json
          clientId=$(jq -r .clientId /tmp/azure_creds.json)
          clientSecret=$(jq -r .clientSecret /tmp/azure_creds.json)
          tenantId=$(jq -r .tenantId /tmp/azure_creds.json)
          # Attempt login and append any errors to the build log
          az login --service-principal -u "$clientId" -p "$clientSecret" --tenant "$tenantId" 2>&1 | tee -a build-devops.log || true
          # cleanup
          shred -u /tmp/azure_creds.json || rm -f /tmp/azure_creds.json || true

      - name: Prepare App Service (create plan + webapp if missing)
        # if azure login fails this will be skipped; deployment will then fail but log upload still runs
        env:
          AZURE_WEBAPP_NAME: ${{ env.AZURE_WEBAPP_NAME }}
          AZURE_RESOURCE_GROUP: ${{ env.AZURE_RESOURCE_GROUP }}
          AZURE_WEBAPP_PLAN: ${{ env.AZURE_WEBAPP_PLAN }}
          AZURE_LOCATION: ${{ env.AZURE_LOCATION || 'eastus' }}
        run: |
          set -e
          if [ -z "$AZURE_WEBAPP_NAME" ] || [ -z "$AZURE_RESOURCE_GROUP" ]; then
            echo "AZURE_WEBAPP_NAME and AZURE_RESOURCE_GROUP must be set as repo secrets to deploy." >&2
            exit 1
          fi
          # default plan name
          if [ -z "$AZURE_WEBAPP_PLAN" ]; then
            AZURE_WEBAPP_PLAN="${AZURE_WEBAPP_NAME}-plan"
            echo "No plan provided. Using $AZURE_WEBAPP_PLAN"
          fi
          # create resource group if missing
          az group create --name "$AZURE_RESOURCE_GROUP" --location "$AZURE_LOCATION" || true
          # create app service plan (Linux, B1) if missing
          az appservice plan show --name "$AZURE_WEBAPP_PLAN" --resource-group "$AZURE_RESOURCE_GROUP" >/dev/null 2>&1 || \
            az appservice plan create --name "$AZURE_WEBAPP_PLAN" --resource-group "$AZURE_RESOURCE_GROUP" --is-linux --sku B1 --output none
          # create webapp (Java 17) if missing
          az webapp show --name "$AZURE_WEBAPP_NAME" --resource-group "$AZURE_RESOURCE_GROUP" >/dev/null 2>&1 || \
            az webapp create --resource-group "$AZURE_RESOURCE_GROUP" --plan "$AZURE_WEBAPP_PLAN" --name "$AZURE_WEBAPP_NAME" --runtime "JAVA|17-java17" --output none

      - name: Deploy JAR to App Service
        env:
          AZURE_WEBAPP_NAME: ${{ env.AZURE_WEBAPP_NAME }}
          AZURE_RESOURCE_GROUP: ${{ env.AZURE_RESOURCE_GROUP }}
        run: |
          set -e
          JAR=$(ls target/*.jar | head -n1)
          if [ -z "$JAR" ]; then echo "Jar not found in target/" >&2; exit 1; fi
          echo "Deploying $JAR to webapp $AZURE_WEBAPP_NAME..."
          az webapp deploy --resource-group "$AZURE_RESOURCE_GROUP" --name "$AZURE_WEBAPP_NAME" --src-path "$JAR" --type jar --restart true

      - name: Upload devops log to Azure Blob (always)
        if: always()
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
        run: |
          set -e
          if [ -z "$AZURE_STORAGE_CONNECTION_STRING" ] || [ -z "$AZURE_STORAGE_CONTAINER" ]; then
            echo "AZURE_STORAGE_CONNECTION_STRING and AZURE_STORAGE_CONTAINER must be provided as secrets for log upload." >&2
            exit 1
          fi
          # ensure container exists
          az storage container create --name "$AZURE_STORAGE_CONTAINER" --connection-string "$AZURE_STORAGE_CONNECTION_STRING" || true
          # upload log (overwrite)
          az storage blob upload \
            --connection-string "$AZURE_STORAGE_CONNECTION_STRING" \
            --container-name "$AZURE_STORAGE_CONTAINER" \
            --name "logs/${{ github.workflow }}-${{ github.run_id }}/build-devops.log" \
            --file build-devops.log \
            --overwrite || true

