name: Trigger auto deployment for deploypetclinic

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/deploypetclinic-AutoDeployTrigger-4f57f678-7e01-4eed-81b0-a9a5f4dea3f9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DEPLOYPETCLINIC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEPLOYPETCLINIC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEPLOYPETCLINIC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.DEPLOYPETCLINIC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEPLOYPETCLINIC_REGISTRY_PASSWORD }}
          containerAppName: deploypetclinic
          resourceGroup: rg-petclinic-92f27e
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


