name: Build and Test Spring Boot Application

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Run Tests
        run: mvn test

      - name: Package Application
        run: mvn package -DskipTests=true

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.0  # Specify the exact version
        with:
          name: spring-boot-app
          path: target/*.jar

      - name: Notify Success
        if: success()
        run: echo "Spring Boot application build and tests completed successfully on self-hosted runner!"
